# Generated by Django 3.2.18 on 2023-04-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230407_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeitem',
            name='Area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscribeitem',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='subscribeitem',
            name='door_number',
            field=models.IntegerField(null=True),
        ),
    ]
