# Generated by Django 3.2.18 on 2023-05-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230408_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bill_option',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='salary_option',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
