# Generated by Django 3.2.18 on 2023-04-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230530_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(blank=True, default=0, null=True)),
                ('previous_Amount', models.IntegerField(blank=True, default=0, null=True)),
                ('previous2months_Amount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='previous2months_Amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='previous_Amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
